name: Tests

on:
    push:
        branches: [ 1.x ]
    pull_request:
        branches: [ 1.x ]

    workflow_dispatch:
jobs:
    tests :
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - "8.1"
                dependency-mode:
                  - prefer-stable
                  - prefer-lowest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2

            - name: Install dependencies
              run: composer install --ansi

            - name: Update  dependencies
              run: composer update --${{ matrix.dependency-mode }} --ansi

            - name: Run code sniffer
              run: ./vendor/bin/phpcs -ps --colors

            - name: Run unit tests
              run: ./vendor/bin/phpunit --colors tests
